Implementing Constant and Calo DistanceToTime
KFTrack/KinKal pull request #172
Opened 2023-05-08 03:26 UTC by rm-rf-ryan

I've rewrote the code within Line to implement various possible Distance to Time relations and added a Geometric Line component, and have also written tests for those.

2023-05-22 20:27 UTC, brownd1978 requested changes
This PR introduces important updates and the code proposed is very well written, there are just a few details to fix.   As this base design will get used in a number of places we want to get the details right.

2023-05-22 20:27 UTC, brownd1978 commented on Trajectory/Line.hh
> +      double speed() const { return d_->speed(0); }
speed without a time no longer makes sense for this class.  Please remove this function, all dependent classes should use speed(time).

2023-05-22 20:27 UTC, brownd1978 commented on Trajectory/Line.hh
> +      TimeRange range() const { return TimeRange(t0() - length()/speed(),t0()); }
range would require an integral to give an accurate answer with a non-linear D2T function.   We need to look where this function is used and decide if it's really needed.  If so, the implementation should be deferred to the D2T function.

2023-05-22 20:27 UTC, brownd1978 commented on Trajectory/Line.hh
> +      std::shared_ptr<DistanceToTime> d_; // change to shared_ptr later
We want to keep t0_ as a member of this class.  That will allow the shared DistanceToTime object to represent a universal physical response, while each individual Line object would model a specific line measurement, having its own unique time.  The corresponding change to DistanceToTime is to assume the function there starts at t=0, and to call D2T::distance(t-t0_) (etc).  It has the advantage of making DistanceToTime a pure virtual interface, which is good programming practice.

2023-05-22 20:27 UTC, brownd1978 commented on Trajectory/DistanceToTime.hh
> +        double timeOffset_;
timeOffset_ (or t0_) should move back to Line.  As far as this class is concerned, time would start at 0.0, so it's response can be used universally.  Downstream callers need to make appropriate updates.

2023-05-22 20:27 UTC, brownd1978 commented on Trajectory/ConstantDistanceToTime.cc
> +    return (deltaT - timeOffset_) * constantSpeed_;
See comments about moving timeOffset_ back to Line, which simplifies this and other functions.

2023-06-14 19:06 UTC, brownd1978 commented on Trajectory/GeometricLine.hh
> +      VEC3 startPosition() const { return pos0_ - length_*dir_; }
The convention that pos0_ is the end is unintuitive.  Can you explain what motivates it?

2023-06-14 19:11 UTC, rm-rf-ryan commented on Trajectory/GeometricLine.hh
> +      VEC3 startPosition() const { return pos0_ - length_*dir_; }
This was actually part of the initial Line code. I kept it since it seems like it would mess up other parts of the code if I changed it, although I haven't actually tried changing it.

2023-06-23 22:21 UTC, brownd1978 reviewed
One small fix and I think this is ready to merge.

2023-06-23 22:21 UTC, brownd1978 commented on Trajectory/Line.hh
> +      double timeHint() const { return length()/(2*d_->speed(100)); }
This 100 is specific to the calorimeter.  I think you want 0.5*length()/d_->speed(0.5*length()));

2023-06-23 22:26 UTC, brownd1978 commented on Trajectory/Line.hh
> +      double timeHint() const { return length()/(2*d_->speed(100)); }
Also t0_ needs to be returned as part of the time hint.  The simplest implementation is:
`timeHint() const { return t0_ + d_->time(0.5*length()); }`
That makes no assumption

2023-06-23 22:26 UTC, brownd1978 commented on Trajectory/Line.hh
> +      std::shared_ptr<DistanceToTime> d_;
1-character variables are not descriptive and can be hard to locate via search.  I suggest renaming this member d2t_

2023-06-26 16:38 UTC, brownd1978 approved these changes

2023-06-26 16:49 UTC, brownd1978 reviewed
I suggested a few minor changes to clarify the interfaces.  After that the PR is ready to merge.

2023-06-26 16:49 UTC, brownd1978 commented on Trajectory/GeometricLine.hh
> +      VEC3 const& direction(double distance) const { return dir_; }
We don't need this function: direction() is a complete description of a geometric line.  That should simplify the code in Line as well.  Line still needs the direction(time) function is because it's required by the ClosestApproach template, but it can be implemented to call GeometricLine::direction()

2023-06-26 16:49 UTC, brownd1978 commented on Trajectory/Line.hh
> +      double timeHint() const { return t0_ + d2t_->time(0.5*length()); }
Given the current implementation, a more descriptive name for this function would be timeAtMidpoint().

2023-06-26 21:45 UTC, merged